name: Keep server awake

on:
  schedule:
    - cron: "*/7 * * * *"   # каждые 7 минут (UTC)
  workflow_dispatch:        # возможность запустить вручную

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    concurrency:
      group: ping-render
      cancel-in-progress: true
    steps:
      - name: Ping /health
        run: |
          code=$(curl -sS -o /dev/null -w "%{http_code}\n" "${PING_URL}")
          echo "HTTP $code"
          test "$code" = "200"
        env:
          PING_URL: ${{ secrets.PING_URL }}