name: Keep server awake

on:
  schedule:
    - cron: "*/7 * * * *"   # каждые 7 минут (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    concurrency:
      group: ping-render
      cancel-in-progress: true

    steps:
      - name: Ping /health with retry
        shell: bash
        env:
          PING_URL: ${{ secrets.PING_URL }}   # https://chaosnet.onrender.com/health
        run: |
          set +e
          echo "Pinging: $PING_URL"
          for i in {1..6}; do
            code=$(curl -sS -o /dev/null -w "%{http_code}" \
                   -L --connect-timeout 10 --max-time 45 \
                   --retry 3 --retry-delay 3 --retry-connrefused \
                   "$PING_URL" || echo 000)
            echo "Attempt $i => HTTP $code"
            if [ "$code" -ge 200 ] && [ "$code" -lt 400 ]; then
              exit 0
            fi
            sleep 10
          done
          echo "Failed to get 2xx/3xx from $PING_URL"
          exit 1