name: Keep server awake

on:
  schedule:
    - cron: "*/7 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    concurrency:
      group: ping-render
      cancel-in-progress: true

    steps:
      - name: Ping /health (retry)
        shell: bash
        env:
          PING_URL: ${{ secrets.PING_URL }}   # например: https://chaosnet.onrender.com/health
        run: |
          echo "Pinging: $PING_URL"
          for i in {1..5}; do
            code=$(curl -I -sS -o /dev/null -w "%{http_code}" \
                   -L --http1.1 \
                   --connect-timeout 10 --max-time 40 \
                   --retry 5 --retry-delay 3 --retry-all-errors \
                   -A "GitHubActions/keepalive" \
                   "$PING_URL" || echo 000)
            echo "Attempt $i => HTTP $code"
            if [ "$code" -ge 200 ] && [ "$code" -lt 400 ]; then
              exit 0
            fi
            sleep 8
          done
          echo "Failed to get 2xx/3xx from $PING_URL"
          exit 1